# Generated by Django 3.1.7 on 2021-03-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210316_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='daricocity@gmail.com', max_length=254, unique=True),
        ),
    ]
