# Generated by Django 3.1.7 on 2021-03-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20210309_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='messageattachment',
            options={'ordering': ('created_at',)},
        ),
    ]
